import React from "react";

function Icon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="50"
      height="50"
      fill="none"
      viewBox="0 0 97 97"
      className="mx-auto "
    >
      <path
        stroke="#FF6A3D"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="8.083"
        d="M48.5 48.5l10.104 8.083M48.5 48.5v36.375V48.5zm0 0l-10.104 8.083L48.5 48.5zM20.346 36.848a16.175 16.175 0 003.904 31.86h4.042"
      ></path>
      <path
        stroke="#FF6A3D"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="8.083"
        d="M63.98 28.85a22.23 22.23 0 00-43.634 8.002s.618 3.565 1.883 5.586"
        ></path>
      <path
        stroke="#FF6A3D"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="8.083"
        d="M68.708 68.708A20.209 20.209 0 1063.98 28.85l-5.375 1.463"
        ></path>
    </svg>
  );
}

export default Icon;